version: '3.5'
services:
  api1:
    image: sousaherbert138/rinha-kotlin:latest
    hostname: api1
    depends_on:
      - db
    environment:
      DB_POOL_SIZE: 3
      DB_ADDRESS: db
      DB_PORT: 5432
      CACHE_PEOPLE_MAX_SIZE: 2
      DB_COROUTINES_PER_POOL: 4
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
    ports:
      - "9999:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
    networks:
      - rinha-network
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2GB'
    networks:
      - rinha-network

networks:
  rinha-network: