version: '3.5'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - api1
      - api2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '256MB'
    networks:
      - rinha-network

  api1:
    image: sousaherbert138/rinha-kotlin:latest
    hostname: api1
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_POOL_SIZE: 4
      DB_ADDRESS: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      CACHE_PEOPLE_MAX_SIZE: 5000
      DB_COROUTINES_PER_POOL: 4
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
    networks:
      - rinha-network

  api2:
    image: sousaherbert138/rinha-kotlin:latest
    hostname: api2
    depends_on:
      - db
    environment:
      PORT: 8081
      DB_POOL_SIZE: 4
      DB_ADDRESS: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      CACHE_PEOPLE_MAX_SIZE: 5000
      DB_COROUTINES_PER_POOL: 4
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
    networks:
      - rinha-network

  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '744MB'
    networks:
      - rinha-network

networks:
  rinha-network: